import { useEffect, useRef, useState, type FormEvent } from 'react';
import { bookingInput, bookingAdditionalServices, type Booking, type BookingInput, type BookingHistory } from '../../shared/bookings';
import { bookingApi } from './booking-api';
import { bookingHallOptions } from '../../shared/halls';
import './bookings.css';
import { permissionEnabled } from '../../shared/staff';
import { useActor } from './StaffAccess';
const empty:BookingInput={customer:'',phone:'',hall:'Hall 1',event:'Walima',date:'',start:'18:00',end:'22:00',guests:100,total:0,manager:'',notes:'',status:'Confirmed',packageName:'',additionalServices:[],holdUntil:null,cancellationReason:''};
export const money=(v:number)=>`PKR ${v.toLocaleString('en-PK')}`;
export default function BookingsWorkspace({rows,onChange,initialId,onClose}:{rows:Booking[];onChange:(b:Booking)=>void;initialId?:string;onClose?:()=>void}){
 const actor=useActor(); const canEdit=permissionEnabled(actor,'booking'),canReceipt=permissionEnabled(actor,'bookingReceipt'),canRefund=permissionEnabled(actor,'bookingRefund'),canPay=canReceipt||canRefund;
 const [selected,setSelected]=useState<Booking|null>(null),[form,setForm]=useState<BookingInput|null>(null),[history,setHistory]=useState<BookingHistory|null>(null);
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('All');
 const createKey=useRef(crypto.randomUUID()),paymentKey=useRef(crypto.randomUUID());
 const paymentPending=useRef<unknown>(null);
 const dirty=!!form && JSON.stringify(form)!==JSON.stringify(selected??empty);
 const closed=selected?.status==='Cancelled'||selected?.status==='Completed';
 useEffect(()=>{const guard=(e:Event)=>{if(busy||(dirty&&!window.confirm('Discard unsaved booking changes?')))e.preventDefault();};window.addEventListener('operations:navigate',guard);return()=>window.removeEventListener('operations:navigate',guard);},[dirty,busy]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 async function open(b:Booking){setSelected(b);setForm({...b,additionalServices:b.additionalServices||[]});setHistory(null);setError('');setMessage('');paymentPending.current=null;paymentKey.current=crypto.randomUUID();try{setHistory(await bookingApi(undefined,b.id));}catch(e){setError((e as Error).message);}}
 useEffect(()=>{if(initialId){const b=rows.find(r=>r.id===initialId);if(b)void open(b);}},[initialId]);
 async function save(e:FormEvent){e.preventDefault();setError('');const parsed=bookingInput.safeParse(form);if(!parsed.success){setError(parsed.error.issues.map(i=>i.message).join(' · '));return;}setBusy(true);try{const b=await bookingApi({action:'save',booking:parsed.data,id:selected?.id??createKey.current,version:selected?.version});onChange(b);setSelected(b);setForm(b);setMessage('Booking saved. Dashboard and calendar are updated.');try{setHistory(await bookingApi(undefined,b.id));}catch{setError('Booking saved, but history could not load. Reopen the booking to retry.');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function pay(e:FormEvent<HTMLFormElement>){e.preventDefault();const element=e.currentTarget;const data=new FormData(element);setBusy(true);setError('');const payload=paymentPending.current??{action:'payment',id:selected!.id,payment:{amount:Number(data.get('amount')),method:data.get('method'),reference:data.get('reference'),kind:data.get('kind'),reason:data.get('reason'),key:paymentKey.current}};paymentPending.current=payload;try{const b=await bookingApi(payload);paymentPending.current=null;paymentKey.current=crypto.randomUUID();onChange(b);setSelected(b);setForm(b);element.reset();setMessage('Transaction recorded.');setHistory(await bookingApi(undefined,b.id));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const change=(k:keyof BookingInput,v:string|number|null)=>setForm(f=>f?{...f,[k]:v}:f);
 const toggleService=(service:BookingInput['additionalServices'][number])=>setForm(f=>f?{...f,additionalServices:f.additionalServices.includes(service)?f.additionalServices.filter(v=>v!==service):[...f.additionalServices,service]}:f);
 const shown=rows.filter(b=>(filter==='All'||b.status===filter||(filter==='Historical'&&(b.status==='Enquiry'||b.status==='Cancelled')))&&`${b.customer} ${b.phone} ${b.hall} ${b.reference}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="booking-workspace"><div className="ops-page-heading"><div><h1>Bookings</h1><p>Manage the occasion, hall arrangements and customer payments.</p></div>{!form&&canEdit&&<button className="ops-button ops-button--gold" onClick={()=>{createKey.current=crypto.randomUUID();setSelected(null);setForm({...empty});setHistory(null);setError('');setMessage('');}}>New booking</button>}</div>
 {error&&<div role="alert" className="booking-error">{error}</div>}{message&&<p role="status" className="booking-success">{message}</p>}
 {form?<section className="ops-panel"><div className="booking-actions"><button className="ops-button ops-button--quiet" disabled={busy} onClick={()=>{if(dirty&&!window.confirm('Discard unsaved booking changes?'))return;setForm(null);setSelected(null);onClose?.();}}>Back to list</button>{selected&&<button className="ops-button ops-button--quiet" onClick={()=>window.print()}>Print booking / payments</button>}</div><h2>{selected?selected.reference:'New booking'}</h2>{selected&&<p>Total {money(selected.total)} · Net received {money(selected.paid)} · {selected.status==='Cancelled'?'Retained amount':'Balance'} {money(selected.status==='Cancelled'?selected.paid:selected.total-selected.paid)}</p>}
 {closed&&<p className="booking-note">This booking is closed. Its details remain in the records. Payment history is available below.</p>}
 <form onSubmit={save} className="booking-fields"><fieldset disabled={busy||closed||!canEdit}>
 {(['customer','phone','date','start','end','guests','total','packageName'] as const).map(k=><label key={k}>{({customer:'Customer name',phone:'Phone number',date:'Event date',start:'Start time (Pakistan)',end:'End time (Pakistan)',guests:'Number of guests',total:'Agreed total (whole PKR)',packageName:'Agreed package'})[k]}<input required={k!=='packageName'} type={k==='date'?'date':['start','end'].includes(k)?'time':['guests','total'].includes(k)?'number':k==='phone'?'tel':'text'} min={k==='guests'?1:undefined} step={['guests','total'].includes(k)?1:undefined} maxLength={k==='phone'?25:160} value={form[k]} onInput={e=>change(k,['guests','total'].includes(k)?Number(e.currentTarget.value):e.currentTarget.value)} /></label>)}
 <label>End date (for overnight events)<input type="date" min={form.date} value={form.endDate||form.date} onInput={e=>change('endDate',e.currentTarget.value)} /></label>
 <label>Halls to reserve<select value={form.hall} onChange={e=>change('hall',e.currentTarget.value)}>{bookingHallOptions.map(v=><option key={v}>{v}</option>)}</select><span>All selected halls are reserved for the same start and end time.</span></label>
 <label>Event<select value={form.event} onChange={e=>change('event',e.currentTarget.value)}>{['Barat','Walima','Mehndi','Nikkah','Corporate','Other'].map(v=><option key={v}>{v}</option>)}</select></label>
 <label>Status<select value={form.status} onChange={e=>change('status',e.currentTarget.value)}>{['Hold','Confirmed','Completed'].map(v=><option key={v}>{v}</option>)}</select></label>
 {form.status==='Hold'&&<label>Hold expiry (Pakistan time)<input required type="datetime-local" value={form.holdUntil?new Date(Date.parse(form.holdUntil)+5*3600000).toISOString().slice(0,16):''} onInput={e=>change('holdUntil',e.currentTarget.value?new Date(e.currentTarget.value+':00+05:00').toISOString():null)} /></label>}
 {form.status==='Cancelled'&&<label>Cancellation reason<textarea required minLength={3} value={form.cancellationReason} onChange={e=>change('cancellationReason',e.currentTarget.value)} /></label>}
 <label>Arrangements and inclusions<textarea maxLength={4000} value={form.notes} onChange={e=>change('notes',e.currentTarget.value)} /></label>
 <fieldset className="booking-additional-services"><legend>Stage</legend><p>Choose whether this booking includes stage setup.</p><div className="booking-service-options booking-service-options--single"><label><input type="checkbox" checked={form.additionalServices.includes('Stage')} onChange={()=>toggleService('Stage')}/><span>Stage</span></label></div></fieldset><fieldset className="booking-additional-services"><legend>Additional services</legend><p>Select every extra arrangement included in this booking. Pricing remains part of the agreed total.</p><div className="booking-service-options">{bookingAdditionalServices.filter(service=>service!=='Stage').map(service=><label key={service}><input type="checkbox" checked={form.additionalServices.includes(service)} onChange={()=>toggleService(service)}/><span>{service}</span></label>)}</div></fieldset>
 </fieldset>{!closed&&canEdit&&<div className="booking-actions"><button className="ops-button ops-button--gold" disabled={busy}>{busy?'Saving…':'Save booking'}</button>{selected&&<button type="button" className="ops-button ops-button--quiet" disabled={busy} onClick={async()=>{if(dirty&&!window.confirm('Reload and discard unsaved changes?'))return;try{const all:Booking[]=await bookingApi();const current=all.find(b=>b.id===selected.id);if(current){onChange(current);await open(current);}}catch(e){setError((e as Error).message);}}}>Reload saved record</button>}</div>}</form>
 {selected&&<><h2>Payments and refunds</h2><p>Record cash received or a verified bank transfer. A refund reason is optional. Save booking edits first.</p>{canPay&&<form onSubmit={pay} className="booking-payment"><fieldset disabled={busy||dirty||!!paymentPending.current}><label>Transaction<select name="kind">{canReceipt&&<option>Receipt</option>}{canRefund&&<option>Refund</option>}</select></label><label>Amount (whole PKR)<input required name="amount" type="number" min="1" step="1" /></label><label>Method<select name="method"><option>Cash</option><option>Bank transfer</option></select></label><label>Bank / receipt reference<input name="reference" maxLength={120} /></label><label>Reason / notes (optional)<input name="reason" maxLength={1000} /></label></fieldset><button className="ops-button ops-button--gold" disabled={busy||dirty}>{busy?'Recording…':paymentPending.current?'Retry same transaction':'Record transaction'}</button>{!!paymentPending.current&&<button type="button" className="ops-button ops-button--quiet" onClick={()=>{paymentPending.current=null;paymentKey.current=crypto.randomUUID();setError('Check the payment history before entering another transaction.');}}>Edit transaction</button>}</form>}
 <h2>Payment history</h2>{history?<><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Date</th><th>Type</th><th>Amount</th><th>Method</th><th>Reference</th></tr></thead><tbody>{history.payments.map(p=><tr key={p.id}><td>{new Date(p.created).toLocaleString('en-PK',{timeZone:'Asia/Karachi'})}</td><td>{p.kind}</td><td>{money(p.amount)}</td><td>{p.method}</td><td>{p.reference||p.id.slice(0,8)}</td></tr>)}</tbody></table></div>{!history.payments.length&&<p>No payments recorded.</p>}<details><summary>Activity history ({history.audit.length})</summary><ul>{history.audit.map(a=><li key={a.id}>{a.action} · {a.actor} · {new Date(a.created).toLocaleString('en-PK',{timeZone:'Asia/Karachi'})}</li>)}</ul></details></>:<p>History unavailable. Reopen the booking to reload it.</p>}</>}
 </section>:<section className="ops-panel"><div className="booking-filters"><label>Search<input value={query} placeholder="Customer, phone, reference or hall" onChange={e=>setQuery(e.currentTarget.value)} /></label><label>Status<select value={filter} onChange={e=>setFilter(e.currentTarget.value)}>{['All','Hold','Confirmed','Completed',...(rows.some(b=>b.status==='Enquiry'||b.status==='Cancelled')?['Historical']:[])].map(v=><option key={v}>{v}</option>)}</select></label></div><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Customer</th><th>Hall / event</th><th>Date</th><th>Status</th><th>Balance</th><th>Record</th></tr></thead><tbody>{shown.map(b=><tr key={b.id}><td><strong>{b.customer}</strong><span>{b.reference} · {b.phone}</span></td><td>{b.hall} · {b.event}{b.additionalServices?.length?<span>Stage/services: {b.additionalServices.join(', ')}</span>:null}</td><td>{b.date}<br/>{b.start}–{b.end}</td><td>{b.status==='Hold'&&Date.parse(b.holdUntil||'')<=Date.now()?'Expired hold':b.status}</td><td>{b.status==='Cancelled'?'Cancelled':money(b.total-b.paid)}</td><td><button className="ops-button ops-button--quiet" onClick={()=>open(b)}>Open</button></td></tr>)}</tbody></table>{!shown.length&&<p>{rows.length?'No bookings match these filters.':'No bookings yet. Create your first booking to begin.'}</p>}</div></section>}
 </div>;
}
