import { useEffect,useRef,useState,type FormEvent } from 'react';
import { pkToday } from '../../shared/staff';
import type { CashReconciliationData,CashHolder } from '../../shared/cash-reconciliation';
import { staffApi } from './staff-api';
import { money } from './BookingsWorkspace';

export default function CashReconciliation(){
 const [date,setDate]=useState(pkToday()),[data,setData]=useState<CashReconciliationData>(),[holder,setHolder]=useState<CashHolder|null>(null);
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 const key=useRef(crypto.randomUUID()),pending=useRef<unknown>(null);
 async function load(){setLoading(true);setError('');try{const response=await fetch(`/api/staff?resource=cash-reconciliation&date=${encodeURIComponent(date)}`,{cache:'no-store'});const result=await response.json();if(!response.ok)throw Error(result.error);setData(result);}catch(e){setData(undefined);setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[date]);
 useEffect(()=>{const guard=(e:Event)=>{if(busy||(holder&&!window.confirm('Discard the unsaved cash count?')))e.preventDefault();};const unload=(e:BeforeUnloadEvent)=>{if(holder){e.preventDefault();e.returnValue='';}};window.addEventListener('operations:navigate',guard);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('operations:navigate',guard);window.removeEventListener('beforeunload',unload);};},[holder,busy]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy||!holder)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');pending.current??={id:key.current,entry:{date,holderKey:holder.key,fingerprint:holder.fingerprint,counted:Number(f.get('counted')),note:f.get('note')}};try{await staffApi('cash-count',pending.current);setHolder(null);pending.current=null;setMessage('Cash count recorded with its ledger balance.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="ops-panel"><h2>Staff cash reconciliation</h2><p>Compare physical cash held with issued cash less recorded spending and returns through the selected date. Count each person’s cash after recording their transactions.</p>
  <div className="booking-actions"><label>Reconciliation date<input type="date" required max={pkToday()} value={date} disabled={!!holder||loading} onChange={e=>{if(e.target.value)setDate(e.target.value);}}/></label><button className="ops-button ops-button--quiet" disabled={!!holder||loading} onClick={load}>Refresh balances</button></div>
  {error&&<p role="alert" className="booking-error">{error}</p>}{message&&<p role="status" className="booking-success">{message}</p>}
  {loading?<p role="status">Loading cash balances…</p>:data&&<><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Cash holder</th><th>Issued</th><th>Spent</th><th>Returned</th><th>Expected cash</th><th>Action</th></tr></thead><tbody>{data.holders.map(h=><tr key={h.key}><td>{h.name}{h.unacknowledged>0&&<span>{h.unacknowledged} handovers awaiting acknowledgement</span>}</td><td>{money(h.issued)}</td><td>{money(h.spent)}</td><td>{money(h.returned)}</td><td>{money(h.expected)}</td><td><button className="ops-button ops-button--quiet" disabled={!!holder} onClick={()=>{key.current=crypto.randomUUID();pending.current=null;setHolder(h);setMessage('');}}>Record cash count</button></td></tr>)}</tbody></table></div>{!data.holders.length&&<p>No issued staff cash to reconcile through this date.</p>}</>}
  {holder&&<form onSubmit={save} className="booking-fields"><h3>Cash count — {holder.name}</h3><p>Expected: {money(holder.expected)} as of {date}.</p><fieldset disabled={busy||!!pending.current}><label>Physically counted (whole PKR)<input name="counted" type="number" min="0" max="10000000000" step="1" required/></label><label>Count notes / explanation of any difference<textarea name="note" required minLength={3} maxLength={1000}/></label></fieldset><div className="booking-actions"><button className="ops-button ops-button--gold" disabled={busy}>{busy?'Saving…':pending.current?'Retry same count':'Save cash count'}</button><button type="button" className="ops-button ops-button--quiet" disabled={busy} onClick={()=>{if(window.confirm('Discard the unsaved cash count?')){setHolder(null);pending.current=null;}}}>Cancel</button></div></form>}
  {!!data?.counts.length&&<><h3>Recorded counts for {date}</h3><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Holder / recorded by</th><th>Expected then</th><th>Counted</th><th>Difference</th><th>Notes / status</th></tr></thead><tbody>{data.counts.map(c=><tr key={c.id}><td>{c.name}<span>{c.actor}</span><span>{new Date(c.created).toLocaleString('en-PK',{timeZone:'Asia/Karachi'})}</span></td><td>{money(c.expected)}</td><td>{money(c.counted)}</td><td>{c.variance===0?'Balanced':`${money(Math.abs(c.variance))} ${c.variance<0?'short':'over'}`}</td><td>{c.note}<span>{c.changed?'Ledger changed since count — review and recount':'Matches ledger snapshot'}</span></td></tr>)}</tbody></table></div></>}
  <p className="booking-note">Cash counts preserve the recorded balance and any shortage or surplus. They do not adjust the ledger or close the accounting period. Staff without a portal account are grouped by the exact cash-recipient name; use distinct names for different people.</p>
 </section>;
}
