import { useEffect,useRef,useState,type FormEvent } from 'react';
import { permissionEnabled, pkToday } from '../../shared/staff';
import type { ExpenseSheet } from '../../shared/registers';
import { useActor } from './StaffAccess';
import { staffApi } from './staff-api';
import { money } from './BookingsWorkspace';
import ExpenseItemField from './ExpenseItemField';
import { defaultExpenseItems } from '../../shared/expense-items';
export default function DailyExpenseSheet(){
 const actor=useActor(),canAdd=permissionEnabled(actor,'expenseAdd'),canRemove=permissionEnabled(actor,'expenseRemove');
 const [day,setDay]=useState(pkToday()),[data,setData]=useState<ExpenseSheet>(),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[adding,setAdding]=useState(false),[remove,setRemove]=useState<string|null>(null),[qty,setQty]=useState(1),[price,setPrice]=useState(0);
 const pending=useRef<unknown>(null),loadVersion=useRef(0);
 async function load(){const version=++loadVersion.current;setLoading(true);setError('');setData(undefined);try{const result=await staffApi<ExpenseSheet>('expense-sheet',undefined,{date:day});if(version===loadVersion.current)setData(result);}catch(e){if(version===loadVersion.current)setError((e as Error).message);}finally{if(version===loadVersion.current)setLoading(false);}}
 useEffect(()=>{setMessage('');void load();return()=>{loadVersion.current++;};},[day]);
 useEffect(()=>{const guard=(e:Event)=>{if(busy||((adding||remove)&&!window.confirm('Discard this unsaved expense form?')))e.preventDefault();};const warn=(e:BeforeUnloadEvent)=>{if(adding||remove){e.preventDefault();e.returnValue='';}};window.addEventListener('operations:navigate',guard);window.addEventListener('beforeunload',warn);return()=>{window.removeEventListener('operations:navigate',guard);window.removeEventListener('beforeunload',warn);};},[adding,remove,busy]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);pending.current??=remove?{id:remove,action:'remove',reason:f.get('reason')}:{id:crypto.randomUUID(),entry:{name:f.get('name'),purpose:f.get('purpose'),quantity:Number(f.get('quantity')),price:Number(f.get('price')),method:f.get('method')}};setBusy(true);setError('');try{await staffApi('expense-sheet',pending.current);pending.current=null;setAdding(false);setRemove(null);setMessage('Expense sheet saved.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="booking-workspace"><div className="ops-page-heading"><div><h1>Daily expense sheet</h1><p>Item, purpose, quantity and price. New entries are dated today in Pakistan.</p></div><button className="ops-button ops-button--quiet" disabled={busy||loading||!!error||data?.date!==day} onClick={()=>window.print()}>Print / save PDF</button></div>
 <div className="booking-actions"><label>Expense date<input type="date" value={day} max={pkToday()} disabled={busy||adding||!!remove} onInput={e=>{if(e.currentTarget.value)setDay(e.currentTarget.value);}}/></label><button className="ops-button ops-button--quiet" disabled={busy||adding||!!remove} onClick={load}>Refresh</button>{canAdd&&day===pkToday()&&!adding&&!remove&&<button className="ops-button ops-button--gold" disabled={loading||!!error} onClick={()=>{pending.current=null;setAdding(true);setQty(1);setPrice(0);setMessage('');}}>Add expense</button>}</div>
 {error&&<p role="alert" className="booking-error">{error}</p>}{message&&<p role="status" className="booking-success">{message}</p>}
 {(adding||remove)&&<section className="ops-panel"><h2>{remove?'Remove expense':'New expense'}</h2><form onSubmit={save} className="booking-fields"><fieldset disabled={busy||!!pending.current}>{remove?<label>Reason for removal<input name="reason" required minLength={3} maxLength={1000}/></label>:<><ExpenseItemField items={data?.items??defaultExpenseItems}/><label>Purpose<input name="purpose" required minLength={2} maxLength={1000}/></label><label>Quantity<input name="quantity" type="number" required min="1" max="1000000" step="1" value={qty} onChange={e=>setQty(Number(e.currentTarget.value))}/></label><label>Price per item (whole PKR)<input name="price" type="number" required min="0" max="100000000" step="1" value={price} onChange={e=>setPrice(Number(e.currentTarget.value))}/></label><label>Paid by<select name="method"><option>Cash</option><option>Bank transfer</option></select></label><p>Total: {money(qty*price)}</p></>}</fieldset><div className="booking-actions"><button className="ops-button ops-button--gold" disabled={busy}>{busy?'Saving…':pending.current?'Retry same entry':remove?'Confirm removal':'Save expense'}</button><button type="button" className="ops-button ops-button--quiet" disabled={busy} onClick={()=>{if(pending.current&&!window.confirm('An earlier request may have saved. Refresh before adding it again. Close?'))return;pending.current=null;setAdding(false);setRemove(null);}}>Cancel</button></div></form></section>}
 {loading?<p role="status">Loading expenses…</p>:!error&&data?.date===day&&<><div className="booking-stats"><div><span>Total expenses</span><strong>{money(data.total)}</strong></div><div><span>Cash spent</span><strong>{money(data.cash)}</strong></div><div><span>Bank paid</span><strong>{money(data.bank)}</strong></div></div><section className="ops-panel"><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Item / purpose</th><th>Qty</th><th>Price</th><th>Total</th><th>Recorded by</th><th>Status</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.id}><td>{r.name}<span>{r.purpose}</span></td><td>{r.quantity}</td><td>{money(r.price)}</td><td>{money(r.amount)}<span>{r.method}</span></td><td>{r.actor}</td><td>{r.removed?'Removed':canRemove?<button className="ops-button ops-button--quiet" disabled={busy||adding||!!remove} onClick={()=>{pending.current=null;setRemove(r.id);}}>Remove</button>:'Recorded'}</td></tr>)}</tbody></table></div>{!data.rows.length&&<p>No expenses recorded for this day.</p>}</section><p>Removed entries stay in history and are excluded from totals. This is spending, not a cash-in-hand balance.</p></>}
 </div>;
}
