import { useEffect, useRef, useState, type FormEvent } from 'react';
import { employeeInput, pkToday, sectors, halls, type Employee, type EmployeeData, type EmployeePayment } from '../../shared/staff';
import { staffApi } from './staff-api';
import { useActor } from './StaffAccess';
import { money } from './BookingsWorkspace';
import { bookingApi } from './booking-api';
import type { Booking } from '../../shared/bookings';
import './bookings.css';

const blank=()=>({name:'',phone:'',sector:'Office',title:'',hall:null,employment:'Permanent',joined:pkToday(),status:'Active',exited:null,exitReason:'',salary:0,salaryEffective:pkToday(),notes:''} as const);
type EmployeeForm=ReturnType<typeof employeeInput.parse>;
export default function EmployeesWorkspace(){
 const actor=useActor(),canEdit=actor.role==='GM',canPay=actor.role!=='Accountant';
 const [data,setData]=useState<EmployeeData>({employees:[],attendance:[],payments:[],audit:[]}),[bookings,setBookings]=useState<Booking[]>([]);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [view,setView]=useState<'Directory'|'Attendance'|'Salary & advances'>('Directory'),[query,setQuery]=useState(''),[month,setMonth]=useState(pkToday().slice(0,7));
 const [selected,setSelected]=useState<Employee|null>(null),[form,setForm]=useState<EmployeeForm|null>(null);
 const [payEmployee,setPayEmployee]=useState<Employee|null>(null),[kind,setKind]=useState<EmployeePayment['kind']>('Salary'),[voidId,setVoidId]=useState<string|null>(null);
 const [attendanceEmployee,setAttendanceEmployee]=useState(''),[day,setDay]=useState(pkToday());
 const key=useRef(crypto.randomUUID()),paymentKey=useRef(crypto.randomUUID()),paymentPending=useRef<unknown>(null);
 async function load(){try{const [records,events]=await Promise.all([staffApi<EmployeeData>('employees'),bookingApi()]);setData(records);setBookings(events);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 const dirty=!!form&&JSON.stringify(form)!==JSON.stringify(selected||blank());
 useEffect(()=>{const guard=(e:Event)=>{if(busy||((dirty||payEmployee)&&!window.confirm('Discard unsaved employee changes?')))e.preventDefault();};const unload=(e:BeforeUnloadEvent)=>{if(dirty||payEmployee){e.preventDefault();e.returnValue='';}};window.addEventListener('operations:navigate',guard);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('operations:navigate',guard);window.removeEventListener('beforeunload',unload);};},[dirty,payEmployee,busy]);
 const change=(key:keyof EmployeeForm,value:unknown)=>setForm(f=>f?{...f,[key]:value}:f);
 async function saveEmployee(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await staffApi<Employee>('employees',{id:selected?.id||key.current,version:selected?.version,entry:form});setSelected(result);setForm(result);await load();setMessage('Employee record saved.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const payments=data.payments.filter(p=>!p.voidedAt);
 const advance=(id:string)=>payments.filter(p=>p.employeeId===id).reduce((s,p)=>s+(p.kind==='Advance'?p.amount:p.kind==='Advance repayment'?-p.amount:0),0);
 function beginPayment(employee:Employee,paymentKind:EmployeePayment['kind']){paymentKey.current=crypto.randomUUID();paymentPending.current=null;setPayEmployee(employee);setKind(paymentKind);setMessage('');setError('');}
 async function markPaid(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);setError('');paymentPending.current??={id:paymentKey.current,entry:{employeeId:payEmployee!.id,kind,deductionRate:Number(d.get('deductionRate')||0),deductionDays:Number(d.get('deductionDays')||0),amount:Number(d.get('amount')),date:d.get('date'),...(kind==='Salary'?{period:month}:{}),method:d.get('method'),reference:d.get('reference'),note:d.get('note'),bookingId:d.get('bookingId')||null}};
 try{await staffApi('payment',paymentPending.current);paymentPending.current=null;setPayEmployee(null);await load();setMessage('Payment marked paid. No money was transferred by the software.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const attendance=data.attendance.find(a=>a.employeeId===attendanceEmployee&&a.date===day);
 async function saveAttendance(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);setError('');try{await staffApi('attendance',{id:attendance?.id||crypto.randomUUID(),version:attendance?.version,entry:{employeeId:attendanceEmployee,date:day,status:d.get('status'),note:d.get('note'),bookingId:d.get('bookingId')||null}});await load();setMessage('Attendance saved. Salary is not changed automatically.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function voidPayment(e:FormEvent<HTMLFormElement>){e.preventDefault();const reason=new FormData(e.currentTarget).get('reason');setBusy(true);setError('');try{await staffApi('void-payment',{id:voidId,reason});setVoidId(null);await load();setMessage('Payment voided with its original history retained.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(loading)return <p role="status">Loading employee records…</p>;
 const shown=data.employees.filter(e=>`${e.name} ${e.title} ${e.sector} ${e.status}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="booking-workspace"><div className="ops-page-heading"><div><h1>Employees</h1><p>People, attendance and payments already made by the venue.</p></div><button className="ops-button ops-button--quiet" disabled={busy||dirty||!!payEmployee} onClick={load}>Refresh</button></div>
 <div className="staff-tabs" role="group" aria-label="Employee sections">{(['Directory','Attendance',...(canPay?['Salary & advances']:[])] as const).map(v=><button key={v} className={`ops-button ${view===v?'ops-button--gold':'ops-button--quiet'}`} disabled={busy} onClick={()=>{if((dirty||payEmployee)&&!window.confirm('Discard unsaved changes?'))return;setView(v as typeof view);setForm(null);setPayEmployee(null);setSelected(null);}}>{v}</button>)}</div>
 {error&&<p className="booking-error" role="alert">{error}</p>}{message&&<p className="booking-success" role="status">{message}</p>}
 {view==='Directory'&&<>
 <div className="booking-actions"><label>Find an employee<input value={query} placeholder="Name, sector, job title or status" onChange={e=>setQuery(e.currentTarget.value)}/></label>{canEdit&&<button className="ops-button ops-button--gold" disabled={busy} onClick={()=>{if(dirty&&!window.confirm('Discard unsaved changes?'))return;key.current=crypto.randomUUID();setSelected(null);setForm({...blank()});}}>Add employee</button>}</div>
 {form&&<section className="ops-panel"><h2>{selected?selected.name:'Recruit employee'}</h2><form className="booking-fields" onSubmit={saveEmployee}><fieldset disabled={!canEdit||busy}>
 <label>Full name<input required maxLength={120} value={form.name} onChange={e=>change('name',e.currentTarget.value)}/></label><label>Phone<input type="tel" maxLength={25} value={form.phone} onChange={e=>change('phone',e.currentTarget.value)}/></label>
 <label>Sector<select value={form.sector} onChange={e=>change('sector',e.currentTarget.value)}>{sectors.map(s=><option key={s}>{s}</option>)}</select></label><label>Job title<input required maxLength={120} value={form.title} onChange={e=>change('title',e.currentTarget.value)}/></label>
 <label>Hall<select value={form.hall||''} onChange={e=>change('hall',e.currentTarget.value||null)}><option value="">Venue-wide</option>{halls.map(h=><option key={h}>{h}</option>)}</select></label><label>Employment<select value={form.employment} onChange={e=>change('employment',e.currentTarget.value)}>{['Permanent','Rental','Daily wage'].map(v=><option key={v}>{v}</option>)}</select></label>
 <label>Recruitment / rehire date<input type="date" required max={pkToday()} value={form.joined} onInput={e=>change('joined',e.currentTarget.value)}/></label><label>Employment status<select value={form.status} onChange={e=>change('status',e.currentTarget.value)}>{['Active','Resigned','Terminated','Retired'].map(v=><option key={v}>{v}</option>)}</select></label>
 <label>Exit date<input type="date" max={pkToday()} value={form.exited||''} onInput={e=>change('exited',e.currentTarget.value||null)}/></label><label>Exit reason<input value={form.exitReason} maxLength={1000} onChange={e=>change('exitReason',e.currentTarget.value)}/></label>
 {canPay&&<><label>{form.employment==='Permanent'?'Agreed monthly salary':'Agreed daily / event rate'} (PKR)<input required type="number" min="0" max="100000000" step="1" value={form.salary} onChange={e=>change('salary',Number(e.currentTarget.value))}/></label><label>Rate effective from<input required type="date" value={form.salaryEffective} onInput={e=>change('salaryEffective',e.currentTarget.value)}/></label></>}
 <label>Notes<textarea maxLength={2000} value={form.notes} onChange={e=>change('notes',e.currentTarget.value)}/></label></fieldset><div className="booking-actions">{canEdit&&<button className="ops-button ops-button--gold" disabled={busy}>Save employee</button>}<button type="button" className="ops-button ops-button--quiet" disabled={busy} onClick={()=>{if(dirty&&!window.confirm('Discard unsaved changes?'))return;setForm(null);setSelected(null);}}>Close record</button></div></form>
 {selected&&canEdit&&<><h3>Outstanding advance: {money(advance(selected.id))}</h3><div className="booking-actions"><button className="ops-button ops-button--quiet" disabled={dirty} onClick={()=>beginPayment(selected,'Advance')}>Record advance</button><button className="ops-button ops-button--quiet" disabled={dirty} onClick={()=>beginPayment(selected,'Advance repayment')}>Record advance repayment</button>{selected.employment!=='Permanent'&&<button className="ops-button ops-button--quiet" disabled={dirty} onClick={()=>beginPayment(selected,'Rental wage')}>Mark wage paid</button>}</div><details><summary>Employment and payment history</summary><ul>{data.audit.filter(a=>a.entity===selected.id).map(a=><li key={a.id}>{a.action} · {a.actor} · {new Date(a.created).toLocaleString('en-PK')}</li>)}</ul></details></>}
 </section>}
 <section className="ops-panel"><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Employee</th><th>Sector / role</th><th>Employment</th><th>Status</th>{canPay&&<th>Agreed rate</th>}<th>Record</th></tr></thead><tbody>{shown.map(e=><tr key={e.id}><td><strong>{e.name}</strong><span>{e.hall||'Venue-wide'}</span></td><td>{e.sector}<span>{e.title}</span></td><td>{e.employment}<span>Joined {e.joined}</span></td><td>{e.status}{e.exited&&<span>Exited {e.exited}</span>}</td>{canPay&&<td>{money(e.salary)}</td>}<td><button className="ops-button ops-button--quiet" onClick={()=>{if(dirty&&!window.confirm('Discard unsaved changes?'))return;setSelected(e);setForm({...e});}}>Open</button></td></tr>)}</tbody></table></div>{!shown.length&&<p>No matching employees. Add the first employee to start the register.</p>}</section>
 </>}
 {view==='Attendance'&&<section className="ops-panel"><h2>Daily attendance</h2><p>Attendance is recorded separately. It does not deduct salary.</p><form onSubmit={saveAttendance} className="booking-fields"><fieldset disabled={busy}><label>Employee<select required value={attendanceEmployee} onChange={e=>setAttendanceEmployee(e.currentTarget.value)}><option value="">Select employee</option>{data.employees.map(e=><option key={e.id} value={e.id}>{e.name} · {e.sector}</option>)}</select></label><label>Date<input type="date" required max={pkToday()} value={day} onInput={e=>{if(e.currentTarget.value)setDay(e.currentTarget.value);}}/></label></fieldset><fieldset disabled={busy||!canEdit}><label>Status<select name="status" key={attendance?.id+':'+attendance?.version+':'+day+':'+attendanceEmployee} defaultValue={attendance?.status||'Present'}>{['Present','Absent','Leave','Half day'].map(s=><option key={s}>{s}</option>)}</select></label><label>Booking assignment (optional)<select name="bookingId" key={'booking'+attendance?.id+day+attendanceEmployee} defaultValue={attendance?.bookingId||''}><option value="">General duty</option>{bookings.map(b=><option key={b.id} value={b.id}>{b.customer} · {b.date} · {b.hall}</option>)}</select></label><label>Note<input name="note" maxLength={500} key={'note'+attendance?.id+day+attendanceEmployee} defaultValue={attendance?.note||''}/></label></fieldset><div className="booking-actions">{canEdit&&<button className="ops-button ops-button--gold" disabled={busy}>{attendance?'Update attendance':'Save attendance'}</button>}</div></form>{attendanceEmployee&&!attendance&&<p>No attendance has been recorded for the selected employee on {day}.</p>}<h3>Recorded for {day}</h3><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Employee</th><th>Status</th><th>Recorded by</th></tr></thead><tbody>{data.attendance.filter(a=>a.date===day).map(a=><tr key={a.id}><td>{data.employees.find(e=>e.id===a.employeeId)?.name}</td><td>{a.status}</td><td>{a.actor}</td></tr>)}</tbody></table></div></section>}
 {view==='Salary & advances'&&<section className="ops-panel"><h2>Monthly salary register</h2><p>After paying outside the software, mark the salary paid here. No automatic transfers or deductions.</p><label>Salary month<input type="month" value={month} disabled={!!payEmployee} max={pkToday().slice(0,7)} onInput={e=>{if(e.currentTarget.value&&!payEmployee)setMonth(e.currentTarget.value);}}/></label><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Employee</th><th>Current agreed salary</th><th>Outstanding advance</th><th>Monthly leaves</th><th>Month status</th></tr></thead><tbody>{data.employees.filter(e=>e.employment==='Permanent'&&e.joined.slice(0,7)<=month&&(!e.exited||e.exited.slice(0,7)>=month)).map(e=>{const paid=payments.find(p=>p.employeeId===e.id&&p.kind==='Salary'&&p.period===month);return <tr key={e.id}><td>{e.name}<span>{e.sector}</span></td><td>{money(e.salary)}</td><td>{money(advance(e.id))}</td><td>{data.attendance.filter(a=>a.employeeId===e.id&&a.date.startsWith(month)&&a.status==='Leave').length} / 4 allowed</td><td>{paid?<><strong>Paid · {money(paid.amount)}</strong><span>{paid.date} · {paid.actor}</span></>:canEdit?<button className="ops-button ops-button--gold" onClick={()=>beginPayment(e,'Salary')}>Mark paid</button>:<span>Not marked paid</span>}</td></tr>;})}</tbody></table></div><button className="ops-button ops-button--quiet" onClick={()=>window.print()}>Print salary register</button></section>}
 {payEmployee&&<section className="ops-panel"><h2>{kind==='Salary'?'Mark salary paid':`Record ${kind.toLowerCase()}`} — {payEmployee.name}</h2><p>Record only money already paid or received. This action does not transfer money.</p><form key={paymentKey.current} onSubmit={markPaid} className="booking-fields"><fieldset disabled={busy||!!paymentPending.current}>
 {kind==='Salary'&&<p>Salary month: {month}. To choose another month, cancel this payment first.</p>}<label>Actual amount (PKR)<input name="amount" required type="number" min="1" step="1" max="100000000" defaultValue={kind==='Salary'||kind==='Rental wage'?payEmployee.salary:undefined}/></label>{kind==='Salary'&&<ManualDeduction key={month} salary={payEmployee.salary} excess={Math.max(0,data.attendance.filter(a=>a.employeeId===payEmployee.id&&a.date.startsWith(month)&&a.status==='Leave').length-4)}/>}<label>Actual payment date<input name="date" required type="date" max={pkToday()} defaultValue={pkToday()}/></label><label>Method<select name="method"><option>Cash</option><option>Bank transfer</option></select></label><label>Reference<input name="reference" maxLength={160}/></label><label>Booking (optional)<select name="bookingId"><option value="">No booking link</option>{bookings.map(b=><option key={b.id} value={b.id}>{b.customer} · {b.date}</option>)}</select></label><label>Note<input name="note" maxLength={1000}/></label></fieldset><div className="booking-actions"><button className="ops-button ops-button--gold" disabled={busy}>{busy?'Recording…':paymentPending.current?'Retry same payment':'Confirm paid record'}</button>{!!paymentPending.current&&<button type="button" className="ops-button ops-button--quiet" onClick={()=>{paymentPending.current=null;setError('Check payment history before changing an uncertain payment.');}}>Edit payment</button>}<button type="button" className="ops-button ops-button--quiet" disabled={busy} onClick={()=>{setPayEmployee(null);paymentPending.current=null;}}>Cancel</button></div></form></section>}
 {canPay&&<section className="ops-panel"><h2>Salary, wage and advance history</h2><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Employee / date</th><th>Type / month</th><th>Amount</th><th>Recorded by</th><th>Status</th></tr></thead><tbody>{data.payments.filter(p=>!selected||p.employeeId===selected.id).map(p=><tr key={p.id}><td>{p.employeeName}<span>{p.date}</span></td><td>{p.kind}<span>{p.period}</span></td><td>{money(p.amount)}<span>{p.method} · {p.reference}</span></td><td>{p.actor}</td><td>{p.voidedAt?`Voided: ${p.voidReason}`:actor.role==='GM'?<button className="ops-button ops-button--quiet" onClick={()=>setVoidId(p.id)}>Void incorrect record</button>:'Recorded'}</td></tr>)}</tbody></table></div>{!data.payments.length&&<p>No payments recorded yet.</p>}{voidId&&<form onSubmit={voidPayment} className="booking-payment"><label>Reason for voiding<input name="reason" required minLength={3} maxLength={1000}/></label><button className="ops-button ops-button--gold" disabled={busy}>Confirm void</button><button type="button" className="ops-button ops-button--quiet" onClick={()=>setVoidId(null)}>Keep record</button></form>}</section>}
 </div>;
}
function ManualDeduction({salary,excess}:{salary:number;excess:number}){
 const [rate,setRate]=useState(0),[days,setDays]=useState(0);
 return <div><p>{excess} leave days above the four-day monthly allowance. Leave both fields at zero to make no deduction.</p><label>GM-chosen deduction per day (PKR)<input name="deductionRate" type="number" min="0" max="100000000" step="1" value={rate} onChange={e=>setRate(Number(e.currentTarget.value))}/></label><label>Days GM chooses to deduct<input name="deductionDays" type="number" min="0" max={excess} step="1" value={days} onChange={e=>setDays(Number(e.currentTarget.value))}/></label><p>Chosen deduction: {money(rate*days)}. Nothing is applied automatically.</p><button type="button" className="ops-button ops-button--quiet" disabled={!rate||!days||salary-rate*days<1||days>excess} onClick={e=>{const form=e.currentTarget.form;if(!form)return;const amount=form.elements.namedItem('amount') as HTMLInputElement;const note=form.elements.namedItem('note') as HTMLInputElement;amount.value=String(salary-rate*days);note.value=`GM applied ${days} excess leave days at PKR ${rate}/day.`;}}>Apply chosen deduction to paid amount</button></div>;
}
