import { useState } from 'react';
import type { LedgerEntry } from '../../shared/expenses';
import { useActor } from './StaffAccess';
import { staffApi } from './staff-api';
type Bill={id:string;name:string;size:number};
export default function ExpenseEvidence({entry,onChange}:{entry:LedgerEntry;onChange:(entry:LedgerEntry)=>void}){
 const actor=useActor();const [open,setOpen]=useState(false),[files,setFiles]=useState<Bill[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[note,setNote]=useState('');
 const status=entry.reviewStatus||'Submitted';
 async function load(){const r=await fetch(`/api/staff?resource=files&expense=${entry.id}`,{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error);setFiles(data);}
 async function upload(file?:File){if(!file)return;setBusy(true);setError('');try{if(file.size>2*1024*1024)throw Error('Maximum file size is 2 MB.');const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Could not read file.'));reader.readAsDataURL(file);});await staffApi('files',{id:crypto.randomUUID(),entry:{expenseId:entry.id,name:file.name,base64}});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function review(next:string){setBusy(true);setError('');try{const r=await fetch('/api/bookings?resource=expenses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'review',id:entry.id,entry:{status:next,note}})});const data=await r.json();if(!r.ok)throw Error(data.error);onChange(data);setNote('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="expense-evidence"><button className="ops-text-button" onClick={()=>{setOpen(!open);if(!open)void load().catch(e=>setError(e.message));}}>{open?'Close details':'Bills & review'}</button>{open&&<div>{error&&<p className="booking-error" role="alert">{error}</p>}{files.map(f=><p key={f.id}><a href={`/api/staff?resource=download&id=${f.id}`}>{f.name} ({Math.ceil(f.size/1024)} KB)</a></p>)}{!files.length&&<p>No bills attached.</p>}{status==='Submitted'&&<label>Attach JPG, PNG or PDF (2 MB)<input type="file" accept="image/jpeg,image/png,application/pdf" disabled={busy} onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label>}{actor.role!=='Hall manager'&&!['Approved','Rejected'].includes(status)&&<><label>Review note<input value={note} maxLength={1000} onChange={e=>setNote(e.target.value)}/></label><div className="booking-actions">{status==='Submitted'&&<button disabled={busy||note.trim().length<3} className="ops-button ops-button--quiet" onClick={()=>review('Verified')}>Verify</button>}{status==='Verified'&&['Director','GM'].includes(actor.role)&&<button disabled={busy||note.trim().length<3} className="ops-button ops-button--gold" onClick={()=>review('Approved')}>Approve</button>}<button disabled={busy||note.trim().length<3} className="ops-button ops-button--quiet" onClick={()=>review('Rejected')}>Reject</button></div></>}{entry.reviews?.map((r,i)=><p key={i}>{r.status} · {r.actor}<br/>{r.note}</p>)}</div>}</div>;
}
