import { useEffect, useRef, useState, type FormEvent } from 'react';
import { expenseCategories, issueRemaining, type LedgerEntry, type LedgerInput } from '../../shared/expenses';
import type { Booking } from '../../shared/bookings';
import { bookingApi } from './booking-api';
import { money } from './BookingsWorkspace';
import './bookings.css';
import { useActor } from './StaffAccess';
import { staffApi } from './staff-api';
import type { StaffUser } from '../../shared/staff';
import ExpenseEvidence from './ExpenseEvidence';

async function ledgerApi(data?:unknown):Promise<LedgerEntry[]|LedgerEntry>{
 const response=await fetch('/api/bookings?resource=expenses',{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined,cache:'no-store'});
 const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to load the expense ledger.');return result;
}
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Karachi',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export default function ExpensesWorkspace(){
 const actor=useActor();const canIssue=['Director','GM'].includes(actor.role);const [accounts,setAccounts]=useState<StaffUser[]>([]);
 useEffect(()=>{if(actor.role!=='Hall manager')void staffApi<StaffUser[]>('users').then(setAccounts).catch(()=>{});},[]);
 const [entries,setEntries]=useState<LedgerEntry[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const [form,setForm]=useState<LedgerInput|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState('');
 const [voidId,setVoidId]=useState<string|null>(null),[reason,setReason]=useState('');
 const key=useRef(crypto.randomUUID()),pending=useRef<unknown>(null);
 async function load(){setError('');try{const [all,events]=await Promise.all([ledgerApi(),bookingApi()]);setEntries(all as LedgerEntry[]);setBookings(events);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{const guard=(e:Event)=>{if(busy||(form&&!window.confirm('Discard the unsaved ledger entry?')))e.preventDefault();};window.addEventListener('operations:navigate',guard);return()=>window.removeEventListener('operations:navigate',guard);},[form,busy]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(form){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[form]);
 const active=entries.filter(e=>!e.voidedAt),issues=active.filter(e=>e.kind==='Cash issue');
 const update=(entry:LedgerEntry)=>setEntries(all=>[entry,...all.filter(e=>e.id!==entry.id)]);
 const change=(patch:Partial<LedgerInput>)=>setForm(f=>f?{...f,...patch}:null);
 function begin(kind:LedgerInput['kind']){key.current=crypto.randomUUID();pending.current=null;setError('');setMessage('');setForm({kind,date:today(),amount:0,person:'',recipientId:null,issuer:actor.name,category:'Other',method:'Cash',reference:'',description:'',bookingId:null,issueId:null});}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');pending.current??={action:'save',id:key.current,entry:form};try{update(await ledgerApi(pending.current) as LedgerEntry);pending.current=null;setForm(null);setMessage('Entry saved to the private ledger.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function confirmVoid(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{update(await ledgerApi({action:'void',id:voidId,reason}) as LedgerEntry);setVoidId(null);setReason('');setMessage('Entry voided. The original record and reason remain visible.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function acknowledge(id:string){setBusy(true);setError('');try{update(await ledgerApi({action:'acknowledge',id}) as LedgerEntry);setMessage('Cash handover acknowledged and retained in the audit trail.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(loading)return <p role="status">Loading cash and expenses…</p>;
 const shown=entries.filter(e=>`${e.person} ${e.description} ${e.category} ${e.date} ${e.reference}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="booking-workspace"><div className="ops-page-heading"><div><h1>Cash & expenses</h1><p>Track cash issued, spending and money returned. Amounts are recorded in whole PKR.</p></div>{!form&&<button className="ops-button ops-button--quiet" onClick={load}>Refresh</button>}</div>
 {error&&<div className="booking-error" role="alert">{error}</div>}{message&&<p className="booking-success" role="status">{message}</p>}
 {!form&&<><div className="booking-actions"><button className="ops-button ops-button--gold" onClick={()=>begin('Expense')}>Record expense</button>{canIssue&&<button className="ops-button ops-button--quiet" onClick={()=>begin('Cash issue')}>Issue cash</button>}<button className="ops-button ops-button--quiet" onClick={()=>begin('Cash return')}>Record cash return</button><button className="ops-button ops-button--quiet" onClick={()=>window.print()}>Print ledger</button></div><div className="booking-stats"><div><span>Recorded expenses · all dates</span><strong>{money(active.filter(e=>e.kind==='Expense').reduce((s,e)=>s+e.amount,0))}</strong></div><div><span>Unsettled issued cash · all dates</span><strong>{money(issues.reduce((s,e)=>s+issueRemaining(e,entries),0))}</strong></div></div></>}
 {form&&<section className="ops-panel"><h2>{form.kind}</h2><form onSubmit={save} className="booking-fields"><fieldset disabled={busy||!!pending.current}>
 <label>Date<input required type="date" value={form.date} onChange={e=>change({date:e.target.value})}/></label><label>Amount (whole PKR)<input required min="1" max="1000000000" step="1" type="number" value={form.amount||''} onChange={e=>change({amount:Number(e.target.value)})}/></label>
 {form.kind!=='Cash issue'&&<label>Cash issue {form.kind==='Expense'?'(optional)':''}<select required={form.kind==='Cash return'} value={form.issueId||''} onChange={e=>{const issue=issues.find(i=>i.id===e.target.value);change({issueId:issue?.id||null,person:issue?.person||'',recipientId:issue?.recipientId||null,method:'Cash'});}}><option value="">{form.kind==='Expense'?'Paid directly — no cash issue':'Select original issue'}</option>{issues.map(i=><option value={i.id} key={i.id}>{i.person} · {i.date} · {money(issueRemaining(i,entries))} remaining · {i.id.slice(0,8)}</option>)}</select></label>}
 <label>{form.kind==='Cash issue'?'Cash recipient':form.issueId?'Cash holder':'Paid to'}<input required readOnly={!!form.issueId} maxLength={120} value={form.person} onChange={e=>change({person:e.target.value})}/></label>
 {form.kind==='Cash issue'&&<label>Portal recipient (for access to this cash)<select value={form.recipientId||''} onChange={e=>{const u=accounts.find(u=>u.id===e.target.value);change({recipientId:u?.id||null,person:u?.name||''});}}><option value="">Other employee without a login</option>{accounts.filter(u=>u.active).map(u=><option key={u.id} value={u.id}>{u.name} · {u.role}</option>)}</select></label>}
 {form.kind==='Cash issue'&&<label>Issued by (Director / GM name)<input required maxLength={120} value={form.issuer} onChange={e=>change({issuer:e.target.value})}/></label>}
 {form.kind==='Expense'&&<><label>Category<select value={form.category} onChange={e=>change({category:e.target.value as LedgerInput['category']})}>{expenseCategories.map(c=><option key={c}>{c}</option>)}</select></label><label>Payment method<select disabled={!!form.issueId} value={form.method} onChange={e=>change({method:e.target.value as LedgerInput['method']})}><option>Cash</option><option>Bank transfer</option></select></label></>}
 <label>Booking (optional)<select value={form.bookingId||''} onChange={e=>change({bookingId:e.target.value||null})}><option value="">General venue expense / cash</option>{bookings.map(b=><option key={b.id} value={b.id}>{b.customer} · {b.date} · {b.hall} · {b.reference}</option>)}</select></label>
 <label>Bill / transfer reference<input required={form.method==='Bank transfer'} maxLength={160} value={form.reference} onChange={e=>change({reference:e.target.value})}/></label><label>Purpose / details<textarea required minLength={3} maxLength={2000} value={form.description} onChange={e=>change({description:e.target.value})}/></label>
 </fieldset><div className="booking-actions"><button className="ops-button ops-button--gold" disabled={busy}>{busy?'Saving…':pending.current?'Retry same entry':'Save entry'}</button>{!!pending.current&&<button type="button" className="ops-button ops-button--quiet" disabled={busy} onClick={()=>{pending.current=null;setError('Review the ledger before changing an entry whose save result was uncertain.');}}>Edit entry</button>}<button type="button" className="ops-button ops-button--quiet" disabled={busy} onClick={()=>{if(window.confirm('Discard this unsaved entry?')){setForm(null);pending.current=null;}}}>Cancel</button></div></form></section>}
 <section className="ops-panel"><h2>Cash with staff</h2><p>Unsettled cash is the issued amount minus recorded spending and returns. Issuing cash is a transfer, not an expense.</p><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Recipient</th><th>Issued by / date</th><th>Issued</th><th>Remaining</th><th>Handover</th></tr></thead><tbody>{issues.map(i=><tr key={i.id}><td>{i.person}<span>{i.id.slice(0,8)}</span></td><td>{i.issuer}<span>{i.date}</span></td><td>{money(i.amount)}</td><td>{money(issueRemaining(i,entries))}</td><td>{i.acknowledgedAt?<span>Acknowledged by {i.acknowledgedBy}</span>:i.recipientId===actor.id?<button className="ops-button ops-button--quiet" disabled={busy} onClick={()=>void acknowledge(i.id)}>Acknowledge receipt</button>:<span>Awaiting recipient</span>}</td></tr>)}</tbody></table></div>{!issues.length&&<p>No cash issued yet. Use “Issue cash” to record a handover.</p>}</section>
 <section className="ops-panel"><h2>Ledger</h2><label>Search ledger<input placeholder="Person, date, category or reference" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Date / type</th><th>Person / details</th><th>Booking</th><th>Amount</th><th>Status</th></tr></thead><tbody>{shown.map(e=><tr key={e.id}><td>{e.date}<span>{e.kind} · {e.method}</span></td><td><strong>{e.person}</strong><span>{e.category} · {e.description}</span><span>{e.reference}</span></td><td>{bookings.find(b=>b.id===e.bookingId)?.reference||'General'}</td><td>{money(e.amount)}</td><td>{e.voidedAt?<span>Voided: {e.voidReason}</span>:<><span>{e.reviewStatus||'Submitted'}</span>{actor.role==='Director'&&<button className="ops-button ops-button--quiet" disabled={busy} onClick={()=>{setVoidId(e.id);setReason('');}}>Void entry</button>}<ExpenseEvidence entry={e} onChange={update}/></>}</td></tr>)}</tbody></table></div>{!shown.length&&<p>No entries match. Record an expense or cash issue to begin.</p>}
 {voidId&&<form onSubmit={confirmVoid} className="booking-payment"><label>Reason for voiding entry {voidId.slice(0,8)}<input required minLength={3} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="ops-button ops-button--gold" disabled={busy}>Confirm void</button><button type="button" className="ops-button ops-button--quiet" disabled={busy} onClick={()=>setVoidId(null)}>Keep entry</button></form>}
 </section><p className="booking-note">Bills are private. Record salary payments in Employees, not again as expenses. Reviews and voids retain the original records.</p></div>;
}
