import { useEffect,useRef,useState,type FormEvent } from 'react';
import { inventoryCategories,locations,movementKinds,unsettled,type InventoryData,type StockItem,type StockMovement } from '../../shared/inventory';
import { pkToday,type EmployeeData } from '../../shared/staff';
import type { Booking } from '../../shared/bookings';
import { staffApi } from './staff-api';
import { bookingApi } from './booking-api';
import { useActor } from './StaffAccess';
import './bookings.css';
import StockTransferForm from './StockTransferForm';
import type { LedgerEntry } from '../../shared/expenses';
export default function InventoryWorkspace(){
 const actor=useActor(),canManage=['Director','GM'].includes(actor.role),canMove=actor.role!=='Accountant';
 const [data,setData]=useState<InventoryData>({items:[],movements:[]}),[employees,setEmployees]=useState<EmployeeData['employees']>([]),[bookings,setBookings]=useState<Booking[]>([]);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState('');
 const [adding,setAdding]=useState(false),[selected,setSelected]=useState<string>(''),[kind,setKind]=useState<StockMovement['kind']>('Issue'),[sourceId,setSourceId]=useState(''),[moving,setMoving]=useState(false);
 const key=useRef(crypto.randomUUID()),pending=useRef<unknown>(null);
 const [transferring,setTransferring]=useState(false);
 const [expenses,setExpenses]=useState<LedgerEntry[]>([]),[expenseError,setExpenseError]=useState('');
 useEffect(()=>{if(!moving||kind!=='Purchase')return;let current=true;setExpenseError('');void fetch('/api/bookings?resource=expenses',{cache:'no-store'}).then(async response=>{const result=await response.json();if(!response.ok)throw Error(result.error||'Unable to load expense records.');if(current)setExpenses(result.filter((entry:LedgerEntry)=>entry.kind==='Expense'&&!entry.voidedAt));}).catch(e=>{if(current)setExpenseError(e.message);});return()=>{current=false;};},[moving,kind]);
 async function load(){setError('');try{const [inventory,staff,events]=await Promise.all([staffApi<InventoryData>('inventory'),staffApi<EmployeeData>('employees'),bookingApi()]);setData(inventory);setEmployees(staff.employees);setBookings(events);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{const guard=(e:Event)=>{if(busy||((adding||moving)&&!window.confirm('Discard unsaved inventory entry?')))e.preventDefault();};const unload=(e:BeforeUnloadEvent)=>{if(adding||moving){e.preventDefault();e.returnValue='';}};window.addEventListener('operations:navigate',guard);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('operations:navigate',guard);window.removeEventListener('beforeunload',unload);};},[adding,moving,busy]);
 const item=data.items.find(i=>i.id===selected),source=data.movements.find(m=>m.id===sourceId);
 const requiresSource=['Return','Damage','Loss','Repair','Recover','Write-off'].includes(kind);
 const sources=data.movements.filter(m=>m.itemId===selected&&unsettled(m,data.movements)>0&&(['Return','Damage','Loss'].includes(kind)?m.kind==='Issue':kind==='Repair'?m.kind==='Damage':kind==='Recover'?m.kind==='Loss':['Damage','Loss'].includes(m.kind)));
 function begin(item:StockItem){if(transferring)return;setSelected(item.id);setMoving(true);setAdding(false);setKind('Issue');setSourceId('');key.current=crypto.randomUUID();pending.current=null;setError('');setMessage('');}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');const resource=adding?'stock-item':'stock-movement';
 pending.current??={id:key.current,entry:adding?{sku:form.get('sku'),name:form.get('name'),category:form.get('category'),location:form.get('location'),unit:form.get('unit'),minimum:Number(form.get('minimum')),notes:form.get('notes')}:{itemId:selected,kind,quantity:Number(form.get('quantity')),date:form.get('date'),sourceId:requiresSource?sourceId:null,bookingId:requiresSource?source?.bookingId||null:kind==='Issue'?form.get('bookingId'):null,employeeId:requiresSource?source?.employeeId||null:kind==='Issue'?form.get('employeeId'):null,expenseId:kind==='Purchase'?form.get('expenseId')||null:null,reference:form.get('reference'),note:form.get('note')}};
 try{await staffApi(resource,pending.current);pending.current=null;setMoving(false);setAdding(false);await load();setMessage('Inventory record saved. Stock counts have been updated.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function cancel(){if(window.confirm('Discard this inventory entry?')){setMoving(false);setAdding(false);pending.current=null;setError('');}}
 if(loading)return <p role="status">Loading saved inventory…</p>;
 const shown=data.items.filter(i=>`${i.sku} ${i.name} ${i.category} ${i.location}`.toLowerCase().includes(query.toLowerCase()));
 const allowedKinds=movementKinds.filter(k=>actor.role==='Director'||actor.role==='GM'?!['Opening','Write-off'].includes(k)||actor.role==='Director':['Issue','Return','Damage','Loss'].includes(k));
 return <div className="booking-workspace"><div className="ops-page-heading"><div><h1>Inventory</h1><p>Know what is usable, issued to an event, damaged or missing.</p></div><button className="ops-button ops-button--quiet" disabled={busy||adding||moving||transferring} onClick={load}>Refresh</button></div>
 {error&&<p role="alert" className="booking-error">{error}</p>}{message&&<p role="status" className="booking-success">{message}</p>}
 {!adding&&!moving&&!transferring&&<div className="booking-actions">{canManage&&<><button className="ops-button ops-button--gold" onClick={()=>{key.current=crypto.randomUUID();pending.current=null;setAdding(true);}}>Add item</button><button className="ops-button ops-button--quiet" onClick={()=>setTransferring(true)}>Transfer stock</button></>}<button className="ops-button ops-button--quiet" onClick={()=>window.print()}>Print stock register</button><label>Find stock<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Item, SKU, category or location"/></label></div>}
 {transferring&&<StockTransferForm items={data.items} onCancel={()=>setTransferring(false)} onSaved={()=>{setTransferring(false);setMessage('Stock transfer saved at both locations.');void load();}}/>}
 {adding&&<section className="ops-panel"><h2>Add inventory item</h2><p>Create one record per item and home location. Quantities are recorded separately below.</p><form onSubmit={submit} className="booking-fields"><fieldset disabled={busy||!!pending.current}><label>Stock code / SKU<input name="sku" required pattern="[A-Za-z0-9-]{2,40}" maxLength={40} placeholder="PLATE-STORE"/></label><label>Item name<input name="name" required minLength={2} maxLength={160}/></label><label>Category<select name="category">{inventoryCategories.map(c=><option key={c}>{c}</option>)}</select></label><label>Home location<select name="location">{locations.map(l=><option key={l}>{l}</option>)}</select></label><label>Unit<input name="unit" required defaultValue="pieces" maxLength={30}/></label><label>Low-stock threshold<input name="minimum" type="number" required min="0" max="1000000" step="1" defaultValue="0"/></label><label>Notes<textarea name="notes" maxLength={1000}/></label></fieldset><Actions busy={busy} pending={!!pending.current} cancel={cancel}/></form></section>}
 {moving&&item&&<section className="ops-panel"><h2>Record movement — {item.name}</h2><p>{item.sku} · {item.location} · {item.available} usable {item.unit}</p><form key={key.current} onSubmit={submit} className="booking-fields"><fieldset disabled={busy||!!pending.current}><label>Movement<select value={kind} onChange={e=>{setKind(e.target.value as StockMovement['kind']);setSourceId('');}}>{allowedKinds.map(k=><option key={k}>{k}</option>)}</select></label><label>Actual movement date<input name="date" required type="date" max={pkToday()} defaultValue={pkToday()}/></label><label>Quantity ({item.unit})<input name="quantity" type="number" required min="1" max="1000000" step="1"/></label>
 {requiresSource&&<label>Original issue / incident<select required value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">Select source record</option>{sources.map(s=><option key={s.id} value={s.id}>{s.kind} · {s.date} · {s.bookingReference} · {unsettled(s,data.movements)} remaining · {s.id.slice(0,8)}</option>)}</select></label>}
 {kind==='Issue'&&<><label>Booking<select name="bookingId" required><option value="">Choose booking</option>{bookings.filter(b=>['Confirmed','Hold'].includes(b.status)).map(b=><option key={b.id} value={b.id}>{b.reference} · {b.customer} · {b.hall} · {b.date}</option>)}</select></label><label>Receiving employee<select name="employeeId" required><option value="">Choose employee</option>{employees.filter(e=>e.status==='Active').map(e=><option key={e.id} value={e.id}>{e.name} · {e.title}</option>)}</select></label></>}
 {kind==='Purchase'&&<label>Paid expense / bill (optional)<select name="expenseId"><option value="">No payment link</option>{expenses.map(e=><option key={e.id} value={e.id}>{e.date} · {e.person} · PKR {e.amount.toLocaleString()} · {e.reference||e.id.slice(0,8)}</option>)}</select>{expenseError&&<span role="alert">{expenseError} You can save stock without a payment link.</span>}</label>}
 <label>{kind==='Purchase'?'Supplier / bill reference':'Paper slip / gate pass reference (optional)'}<input name="reference" required={kind==='Purchase'} maxLength={160}/></label><label>Reason / details<textarea name="note" required minLength={3} maxLength={1000}/></label></fieldset>{['Damage','Loss','Write-off'].includes(kind)&&<p className="booking-note">Record the actual incident. This does not charge the customer or deduct employee pay. Write-offs require Director access.</p>}{kind==='Purchase'&&<p className="booking-note">This records stock received only. Record its cost and private bill in Cash & expenses; do not record the payment twice.</p>}<Actions busy={busy} pending={!!pending.current} cancel={cancel}/></form></section>}
 <section className="ops-panel"><h2>Stock register</h2><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Item / home</th><th>Usable now</th><th>Issued</th><th>Damaged</th><th>Missing</th><th>Written off</th><th>Action</th></tr></thead><tbody>{shown.map(i=><tr key={i.id}><td><strong>{i.name}</strong><span>{i.sku} · {i.location} · {i.unit}</span></td><td>{i.available}{i.available<=i.minimum&&<span>Low stock</span>}</td><td>{i.issued}</td><td>{i.damaged}</td><td>{i.missing}</td><td>{i.writtenOff}</td><td>{canMove&&<button className="ops-button ops-button--quiet" disabled={busy||adding||moving||transferring} onClick={()=>begin(i)}>Record movement</button>}</td></tr>)}</tbody></table></div>{!shown.length&&<p>{data.items.length?'No items match this search.':'No inventory recorded yet. Add an item, then the Director can enter its opening count.'}</p>}</section>
 <section className="ops-panel"><h2>Movement history</h2><p>Permanent records link stock to the booking and receiving employee. For an incorrect issue, record its return; never delete the original.</p><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Date / item</th><th>Movement</th><th>Quantity</th><th>Booking / employee</th><th>Details</th><th>Recorded by</th></tr></thead><tbody>{data.movements.filter(m=>!selected||m.itemId===selected).map(m=><tr key={m.id}><td>{m.date}<span>{m.itemName}</span></td><td>{m.kind}</td><td>{m.quantity}</td><td>{m.bookingReference||'Venue stock'}<span>{m.employeeName}</span></td><td>{m.note}<span>{m.reference}{m.transferLocation?` · ${m.kind==='Transfer in'?'From':'To'} ${m.transferLocation}`:''}</span></td><td>{m.actor}</td></tr>)}</tbody></table></div>{selected&&<button className="ops-text-button" disabled={moving} onClick={()=>setSelected('')}>Show all items’ history</button>}{!data.movements.length&&<p>No stock movements yet.</p>}</section><p className="booking-note">Use Supplier rentals for hired goods. Transfers move owned stock between locations. Future stock reservations are still pending.</p></div>;
}
function Actions({busy,pending,cancel}:{busy:boolean;pending:boolean;cancel:()=>void}){return <div className="booking-actions"><button className="ops-button ops-button--gold" disabled={busy}>{busy?'Saving…':pending?'Retry same record':'Save record'}</button><button type="button" className="ops-button ops-button--quiet" disabled={busy} onClick={cancel}>Cancel</button>{pending&&<p>Entry kept for a safe retry. If its details need correction, cancel and start a new entry after checking saved history.</p>}</div>;}
