import { useEffect, useState } from 'react';
import { pkToday } from '../../shared/staff';
import { money } from './BookingsWorkspace';
type Row={id:string;kind:string;person:string;amount:number;method:string;status:string;category?:string;item?:string;purpose?:string;quantity?:number;price?:number};
export default function ReportsWorkspace(){
 const [day,setDay]=useState(pkToday()),[rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setRows([]);fetch(`/api/staff?resource=report&date=${day}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setRows(d.rows);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[day,refresh]);
 const groups=['Booking receipt','Customer refund','Expense','Salary','Rental wage','Advance','Advance repayment',...(['Cash issue','Cash return'].filter(kind=>rows.some(row=>row.kind===kind)))];
 return <div className="booking-workspace"><div className="ops-page-heading"><div><h1>Daily income & expenses</h1><p>Shafi Complex & Marquee · Pakistan time · {day}</p></div><button className="ops-button ops-button--gold" disabled={loading||!!error} onClick={()=>window.print()}>Print / save PDF</button></div><label>Report date<input type="date" value={day} max={pkToday()} required onInput={e=>{if(e.currentTarget.value)setDay(e.currentTarget.value);}}/></label><button className="ops-button ops-button--quiet" disabled={loading} onClick={()=>setRefresh(v=>v+1)}>Refresh report</button>{error&&<p className="booking-error" role="alert">{error} Use Refresh report to try again.</p>}{loading?<p role="status">Loading report…</p>:!error&&<><section className="ops-panel"><h2>Daily totals</h2><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Record type</th><th>Cash</th><th>Bank transfer</th><th>Total</th></tr></thead><tbody>{groups.map(kind=><tr key={kind}><td>{kind}</td>{['Cash','Bank transfer','All'].map(method=><td key={method}>{money(rows.filter(r=>r.kind===kind&&(method==='All'||r.method===method)).reduce((s,r)=>s+r.amount,0))}</td>)}</tr>)}</tbody></table></div></section><p className="booking-note">Cash issues and returns are internal transfers, not income or expenses. Salary advances and repayments are tracked separately. All non-void records are shown, including pending and rejected reviews; rejection does not undo an actual payment. This is a daily activity report, not a profit or bank-balance statement.</p><section className="ops-panel"><h2>Supporting records</h2><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Person</th><th>Type / details</th><th>Method</th><th>Amount</th><th>Review</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.person}</td><td>{r.kind}{r.kind==='Expense'&&<><strong>{r.category}</strong><span>{r.item}</span><span>{r.purpose}</span><span>{r.quantity} × {money(r.price??r.amount)}</span></>}</td><td>{r.method}</td><td>{money(r.amount)}</td><td>{r.status}</td></tr>)}</tbody></table></div>{!rows.length&&<p>No recorded transactions on this date.</p>}</section></>}</div>;
}
