import { createContext, useContext, useEffect, useState, useRef, type FormEvent, type ReactNode } from 'react';
import type { Actor, StaffUser } from '../../shared/staff';
import { accountantPermissionGroups, isBuiltInRole } from '../../shared/staff';
import { staffApi } from './staff-api';
import './bookings.css';
import './account-permissions.css';
const Context=createContext<Actor|null>(null);
export const useActor=()=>useContext(Context)!;
export function StaffAccess({children}:{children:ReactNode}){
 const [actor,setActor]=useState<Actor|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const refresh=()=>{setLoading(true);setError('');staffApi<Actor>('session').then(setActor).catch(e=>{if(e.status!==401)setError(e.message);}).finally(()=>setLoading(false));};
 useEffect(refresh,[]);
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);setError('');try{setActor(await staffApi('login',{username:data.get('username'),password:data.get('password')}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(loading)return <p className="staff-loading" role="status">Opening staff portal…</p>;
 if(!actor)return <main className="staff-login booking-workspace"><h1>Staff portal</h1><p>Shafi Complex & Marquee</p>{error&&<p className="booking-error" role="alert">{error}</p>}<form onSubmit={login}><label>Username<input required name="username" autoComplete="username" maxLength={60}/></label><label>Password<input required name="password" type="password" autoComplete="current-password" maxLength={128}/></label><button className="ops-button ops-button--gold" disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form><p><a href="/admin/login" onClick={e=>{e.preventDefault();void staffApi('logout',{}).then(()=>window.location.assign('/admin/login')).catch(e=>setError(e.message));}}>Director / existing owner sign-in</a></p><button className="ops-button ops-button--quiet" onClick={refresh}>Check existing sign-in</button></main>;
 return <Context.Provider value={actor}>{children}</Context.Provider>;
}
export async function logoutStaff(){
 await staffApi('logout',{});
 await fetch('/api/cms?action=logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});
 window.location.assign('/management');
}
export function AccountsWorkspace(){
 const actor=useActor(),key=useRef<string>(crypto.randomUUID());
 const [rows,setRows]=useState<StaffUser[]>([]),[editing,setEditing]=useState(false),[selected,setSelected]=useState<StaffUser|null>(null),[roleChoice,setRoleChoice]=useState<string>('Accountant'),[customRole,setCustomRole]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const load=()=>staffApi<StaffUser[]>('users').then(setRows).catch(e=>setError(e.message));useEffect(()=>{void load();},[]);
 useEffect(()=>{const guard=(e:Event)=>{if(busy||(editing&&!window.confirm('Discard this unsaved account form?')))e.preventDefault();};window.addEventListener('operations:navigate',guard);return()=>window.removeEventListener('operations:navigate',guard);},[editing,busy]);
 function beginAdd(){key.current=crypto.randomUUID();setSelected(null);setRoleChoice('Accountant');setCustomRole('');setError('');setEditing(true);}
 function beginEdit(user:StaffUser){key.current=user.id;setSelected(user);setRoleChoice(isBuiltInRole(user.role)&&user.role!=='Hall manager'?user.role:'__new__');setCustomRole(isBuiltInRole(user.role)?'':user.role);setError('');setEditing(true);}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const role=roleChoice==='__new__'?String(f.get('customRole')||'').trim():roleChoice;if(roleChoice==='__new__'&&!role){setError('Enter a name for the new role.');return;}setBusy(true);setError('');try{await staffApi('users',{id:selected?.id||key.current,entry:{name:f.get('name'),username:f.get('username'),role,hall:null,active:f.get('active')==='on',permissions:Object.fromEntries(Object.values(accountantPermissionGroups).flat().map(permission=>[permission,f.get('perm-'+permission)==='on'])),...(f.get('password')?{password:f.get('password')}:{})}});setEditing(false);setMessage('Account saved. Existing sessions for this account have been signed out.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(actor.role!=='GM')return <p role="alert">Only the GM can manage staff access.</p>;
 const customEditing=roleChoice==='__new__';
 return <div className="booking-workspace"><div className="ops-page-heading"><div><h1>Staff accounts</h1><p>GM manages operations. Director monitors. Accountant adds and removes daily expenses.</p></div><button className="ops-button ops-button--gold" disabled={busy||editing} onClick={beginAdd}>Add account</button></div>{error&&<p role="alert" className="booking-error">{error}</p>}{message&&<p role="status" className="booking-success">{message}</p>}{editing&&<section className="ops-panel"><form onSubmit={save} className="booking-fields" key={key.current}><fieldset disabled={busy}><label>Full name<input name="name" required minLength={2} maxLength={120} defaultValue={selected?.name}/></label><label>Username<input name="username" required pattern="[a-z0-9._-]{3,60}" defaultValue={selected?.username}/></label><label>Role<select name="role" value={roleChoice} onChange={e=>setRoleChoice(e.currentTarget.value)}><option value="Accountant">Accountant</option><option value="GM">GM</option><option value="Director">Director</option><option value="__new__">Add new role…</option></select></label>{customEditing&&<label>New role name<input name="customRole" required minLength={2} maxLength={60} pattern="[A-Za-z0-9][A-Za-z0-9 &._/-]*" value={customRole} onChange={e=>setCustomRole(e.currentTarget.value)} placeholder="e.g. Operations assistant"/><small className="field-hint">Custom roles use only the permission categories you select below.</small></label>}<label>{selected?'New password (leave empty to keep)':'Password'}<input name="password" type="password" required={!selected} minLength={8} maxLength={128} autoComplete="new-password"/></label><label><input type="checkbox" name="active" defaultChecked={selected?.active??true}/>Account active</label>{(roleChoice==='Accountant'||customEditing)&&<PermissionMatrix selected={selected} custom={customEditing}/>}</fieldset><div className="booking-actions"><button className="ops-button ops-button--gold" disabled={busy}>Save account</button><button type="button" className="ops-button ops-button--quiet" disabled={busy} onClick={()=>setEditing(false)}>Cancel</button></div></form></section>}<section className="ops-panel"><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Name</th><th>Username</th><th>Access</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.filter(u=>u.role!=='Hall manager').map(u=><tr key={u.id}><td>{u.name}</td><td>{u.username}</td><td>{u.role}</td><td>{u.active?'Active':'Disabled'}</td><td><button className="ops-button ops-button--quiet" disabled={busy||editing} onClick={()=>beginEdit(u)}>Edit</button></td></tr>)}</tbody></table></div></section></div>;
}

function PermissionMatrix({selected,custom}:{selected:StaffUser|null;custom:boolean}){return <div className="account-permissions"><strong>{custom?'Custom role permissions':'Accountant permissions'}</strong><p>{custom?'Choose the least access this role needs. It will not inherit GM or Director authority.':'Choose All for a category, or enable individual actions.'}</p>{Object.entries(accountantPermissionGroups).map(([group,keys])=>{const all=keys.every(permission=>!!selected?.permissions?.[permission]);return <fieldset key={group} className="permission-group"><legend>{group}</legend><label className="permission-all"><input type="checkbox" name={"perm-all-"+group} defaultChecked={all} onChange={e=>{const form=e.currentTarget.form;if(form)keys.forEach(permission=>{const input=form.elements.namedItem("perm-"+permission) as HTMLInputElement|null;if(input)input.checked=e.currentTarget.checked;});}}/>All</label>{keys.map(permission=><label key={permission}><input type="checkbox" name={"perm-"+permission} defaultChecked={!!selected?.permissions?.[permission]}/>{permission}</label>)}</fieldset>})}</div>}
