import { randomUUID } from 'node:crypto';
import type { PoolClient } from 'pg';
import { z } from 'zod';
import { bookingPool } from './postgres-bookings.js';
import { requireRole } from './staff-auth.js';
import { pkToday,type Actor } from '../shared/staff.js';
import { expenseRowInput,simpleItemInput,itemActionInput,monthInput,sheetDate,type ExpenseSheet,type InventoryRegister,type MonthSummary } from '../shared/registers.js';
import { stockTotals,type StockMovement } from '../shared/inventory.js';
async function transaction<T>(locks:number[],run:(c:PoolClient)=>Promise<T>){const c=await bookingPool().connect();try{await c.query('BEGIN');await c.query("SET LOCAL lock_timeout='8s'");for(const lock of locks)await c.query('SELECT pg_advisory_xact_lock($1)',[lock]);const result=await run(c);await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
export async function expenseSheet(actor:Actor,raw:string|null):Promise<ExpenseSheet>{requireRole(actor,['GM','Director','Accountant']);const date=sheetDate.parse(raw||pkToday());const records=(await bookingPool().query("SELECT body FROM shafi_expenses WHERE body->>'kind'='Expense' AND body->>'date'=$1 ORDER BY created,id",[date])).rows.map(r=>r.body);const rows=records.map(r=>({id:r.id,date:r.date,name:r.name||r.category||'Expense',purpose:r.purpose||r.description,quantity:r.quantity??1,price:r.price??r.amount,amount:r.amount,method:r.method,actor:r.actor,removed:!!r.voidedAt}));const active=rows.filter(r=>!r.removed);return {date,rows,total:active.reduce((s,r)=>s+r.amount,0),cash:active.filter(r=>r.method==='Cash').reduce((s,r)=>s+r.amount,0),bank:active.filter(r=>r.method==='Bank transfer').reduce((s,r)=>s+r.amount,0)};}
export async function addExpenseRow(actor:Actor,id:string,raw:unknown){requireRole(actor,['GM','Accountant']);const input=expenseRowInput.parse(raw);return transaction([7352420],async c=>{const existing=(await c.query('SELECT body FROM shafi_expenses WHERE id=$1',[id])).rows[0]?.body;if(existing){if(existing.ownerId!==actor.id||Object.entries(input).some(([k,v])=>existing[k]!==v))throw Error('Expense retry differs from saved record.');return existing;}const row={...input,id,date:pkToday(),amount:input.price*input.quantity,kind:'Expense',person:actor.name,description:input.purpose,category:'Other',issueId:null,recipientId:null,bookingId:null,reference:'',issuer:'',actor:actor.name,ownerId:actor.id,created:new Date().toISOString(),voidedAt:null,voidReason:null,reviewStatus:'Recorded'};await c.query('INSERT INTO shafi_expenses(id,body) VALUES($1,$2)',[id,JSON.stringify(row)]);return row;});}
export async function removeExpenseRow(actor:Actor,id:string,raw:unknown){requireRole(actor,['GM','Accountant']);const reason=z.string().trim().min(3).max(1000).parse(raw);return transaction([7352420],async c=>{const row=(await c.query('SELECT body FROM shafi_expenses WHERE id=$1',[id])).rows[0]?.body;if(!row||row.kind!=='Expense')throw Error('Expense not found.');if(row.voidedAt)return row;row.voidedAt=new Date().toISOString();row.voidReason=reason;row.reviews=[...(row.reviews||[]),{status:'Removed',note:reason,actor:actor.name,date:row.voidedAt}];await c.query('UPDATE shafi_expenses SET body=$2 WHERE id=$1',[id,JSON.stringify(row)]);return row;});}
export async function inventoryRegister(actor:Actor):Promise<InventoryRegister>{requireRole(actor,['GM','Director']);return transaction([],async c=>{await c.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');const items=(await c.query('SELECT body FROM shafi_stock_items ORDER BY body->>\'name\'')).rows.map(r=>r.body);const moves=(await c.query('SELECT body FROM shafi_stock_movements ORDER BY body->>\'created\' DESC,id')).rows.map(r=>r.body as StockMovement);return {items:items.map(i=>({...i,...stockTotals(moves.filter(m=>m.itemId===i.id)),archived:!!i.archived})),history:moves};});}
export async function addInventoryItem(actor:Actor,id:string,raw:unknown){requireRole(actor,['GM']);const input=simpleItemInput.parse(raw);return transaction([7352419,7352422,7352423],async c=>{const old=(await c.query('SELECT body FROM shafi_stock_items WHERE id=$1',[id])).rows[0]?.body;if(old){if(old.name!==input.name||old.unit!==input.unit||old.openingQuantity!==input.quantity)throw Error('Retry differs from saved item.');return old;}const row={...input,id,openingQuantity:input.quantity,sku:'ITEM-'+id.toUpperCase(),location:'Store',category:'Other',minimum:0,created:new Date().toISOString()};await c.query('INSERT INTO shafi_stock_items(id,sku,body) VALUES($1,$2,$3)',[id,row.sku,JSON.stringify(row)]);if(input.quantity)await appendMovement(c,actor,id,{kind:'Opening',quantity:input.quantity,note:'Initial quantity entered by GM',bookingId:null,sourceId:null},randomUUID(),row.name);return row;});}
async function appendMovement(c:PoolClient,actor:Actor,itemId:string,data:{kind:string;quantity:number;note:string;bookingId:string|null;sourceId:string|null},id:string,name:string,bookingReference=''){const movement={...data,id,itemId,itemName:name,date:pkToday(),employeeId:null,expenseId:null,hall:null,reference:'',employeeName:'',bookingReference,actor:actor.name,created:new Date().toISOString()};await c.query('INSERT INTO shafi_stock_movements(id,item,source,booking,body) VALUES($1,$2,$3,$4,$5)',[id,itemId,data.sourceId,data.bookingId,JSON.stringify(movement)]);return movement;}
export async function inventoryAction(actor:Actor,id:string,raw:unknown){requireRole(actor,['GM']);const input=itemActionInput.parse(raw);return transaction([7352419,7352422,7352423],async c=>{const existing=(await c.query('SELECT body FROM shafi_stock_movements WHERE id=$1',[id])).rows[0]?.body;if(existing){if(!existing.request||Object.entries(input).some(([key,value])=>existing.request[key]!==value))throw Error('Retry differs from saved action.');return existing;}const item=(await c.query('SELECT body FROM shafi_stock_items WHERE id=$1',[input.itemId])).rows[0]?.body;if(!item||item.archived)throw Error('Choose an active item.');const moves=(await c.query('SELECT body FROM shafi_stock_movements WHERE item=$1',[item.id])).rows.map(r=>r.body as StockMovement);const totals=stockTotals(moves);let bookingReference='';if(input.bookingId){const b=(await c.query('SELECT body FROM shafi_bookings WHERE id=$1',[input.bookingId])).rows[0]?.body;if(!b)throw Error('Booking not found.');bookingReference=b.reference;}
 let kind:string=input.action;
 if(!['Replaced','Write off damage'].includes(input.action)&&input.sourceId)throw Error('This action cannot use a source.');
 if(input.action==='Add quantity')kind='Purchase';
 if(input.action==='Damaged'){if(!input.bookingId)throw Error('Select the booking where damage happened.');if(input.quantity>totals.available)throw Error('Damage exceeds available stock. Settle any old stock issues first.');kind='Register damage';}
 if(input.action==='Remove quantity'){if(input.quantity>totals.available)throw Error('Removal exceeds available stock.');kind='Register removal';}
 if(['Replaced','Write off damage'].includes(input.action)){const source=moves.find(m=>m.id===input.sourceId);if(!source||!['Damage','Register damage'].includes(source.kind))throw Error('Select the damage entry being replaced.');const remaining=source.quantity-moves.filter(m=>m.sourceId===source.id).reduce((s,m)=>s+m.quantity,0);if(input.quantity>remaining)throw Error('Replacement exceeds unresolved damage.');if(input.bookingId!==source.bookingId)throw Error('Replacement must retain the original booking.');kind=input.action==='Replaced'?'Register replacement':'Register damage removal';}
 if(input.action==='Archive'){if(totals.issued||totals.damaged||totals.missing)throw Error('Resolve issued, damaged and missing items before removing the item.');item.archived=true;item.archivedBy=actor.name;item.archivedAt=new Date().toISOString();await c.query('UPDATE shafi_stock_items SET body=$2 WHERE id=$1',[item.id,JSON.stringify(item)]);kind='Register archive';}
 const movement=await appendMovement(c,actor,item.id,{kind,quantity:input.action==='Archive'?totals.available:input.quantity,note:input.note,bookingId:input.bookingId,sourceId:input.sourceId},id,item.name,bookingReference);const result={...movement,request:input};await c.query('UPDATE shafi_stock_movements SET body=$2 WHERE id=$1',[id,JSON.stringify(result)]);return result;});}
export async function monthlySummary(actor:Actor,raw:string|null):Promise<MonthSummary>{requireRole(actor,['GM','Director']);const month=monthInput.parse(raw||pkToday().slice(0,7));const date=new Date(month+'-01T00:00:00Z');date.setUTCMonth(date.getUTCMonth()-1);const previousMonth=date.toISOString().slice(0,7);return transaction([],async c=>{await c.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');const payments=(await c.query("SELECT body FROM shafi_booking_payments WHERE to_char(created AT TIME ZONE 'Asia/Karachi','YYYY-MM')=$1",[month])).rows.map(r=>r.body);const receipts=payments.filter(p=>p.kind!=='Refund').reduce((s,p)=>s+p.amount,0),refunds=payments.filter(p=>p.kind==='Refund').reduce((s,p)=>s+p.amount,0);const expenses=(await c.query("SELECT substring(body->>'date',1,7) AS period,SUM((body->>'amount')::numeric) total FROM shafi_expenses WHERE body->>'kind'='Expense' AND body->>'voidedAt' IS NULL AND substring(body->>'date',1,7)=ANY($1::text[]) GROUP BY 1",[[month,previousMonth]])).rows;const current=Number(expenses.find(e=>e.period===month)?.total||0),previous=Number(expenses.find(e=>e.period===previousMonth)?.total||0);const leaves=(await c.query("SELECT e.id,e.body->>'name' name,COUNT(*)::int leaves FROM shafi_attendance a JOIN shafi_employees e ON e.id=a.employee WHERE to_char(a.day,'YYYY-MM')=$1 AND a.body->>'status'='Leave' GROUP BY e.id HAVING COUNT(*)>4 ORDER BY COUNT(*) DESC",[month])).rows;const bookings=Number((await c.query("SELECT COUNT(*) total FROM shafi_bookings WHERE substring(body->>'date',1,7)=$1 AND body->>'status'<>'Cancelled'",[month])).rows[0].total);return {month,previousMonth,receipts,refunds,netReceipts:receipts-refunds,expenses:current,previousExpenses:previous,changePercent:previous?Math.round((current-previous)/previous*10000)/100:null,bookings,leaves:leaves.map(r=>({...r,excess:r.leaves-4}))};});}
